### PR TITLE
Update Bodensee

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DO1JLR** [comment]
Are you kidding me?

@JoniArida I have two questions for you:

1. Why are you doing this? *(Don't you saw #24 and #25 ???)*
2. Do you will be around on Sunday? [General Assembly FFBSEE e.V.](https://ffbsee.net/en/kalender/)

---
Anyone: Please tag this pull request as ``invalid`` and ``dublicated``!

**Review by DO1JLR — CHANGES_REQUESTED** [review]
Overlaps with #24 and #25.

Changes in backend are nececcary bevore changing this link!!!

**Comment by genofire** [comment]
i think about merging #24 - but it will not solve it ...

**Comment by DO1JLR** [comment]
yes... someone should fix the ffbsee backend...

I am extremly sorry but currently I spend my freetime in fixing [Toolbox](https://github.com/toolboxbodensee) Network Issues and [Waffle](https://c3woc.de) ideas for 36c3...

**Comment by ghost** [comment]
> @JoniArida I have two questions for you:
> 
>     1. Why are you doing this? _(Don't you saw #24 and #25 ???)_
Oh.. Actually no, I didn't.
>
>     2. Do you will be around on Sunday? [General Assembly FFBSEE e.V.](https://ffbsee.net/en/kalender/)
Also not, sorry...

**Pull request closed without merging**
