### PR TITLE
Add Dresden

### PR DESCRIPTION
**Pull request by ddmesh**

### CODE REVIEW

**Comment by genofire** [comment]
Works: https://data.meshviewer.org/collector/ ;)

**Comment by ddmesh** [comment]
Danke. Aber ich habe probleme mit der karte https://multi.meshviewer.org.
ich sehe nur Punkte, keine Karte (egal welcher Browser).
Kann leider noch keine Knoten von Dresden in der der Karte finden.
Ne Idee?

**Comment by genofire** [comment]
`invalid NodeID` - we need 12 digits (like the mac address) 

a right pad with zeros would work, but creates a side effect by collision with nodes from other communities ...

**Comment by ddmesh** [comment]
I see what I can do.

**Comment by hibo98** [comment]
Hey, I am developing the backend software ([ViewerBackend](https://github.com/hibo98/ViewerBackend)), which is generating the JSON files for HopGlass and MeshViewer in Dresden. I've search for the problem in the files for a long time. Thank you @genofire  for pointing out where the problem is. I've fixed it a few days ago and it seems to work. I've used the same schema for the id as for the fake mac address. The id starts always with `ffdd0000`, then the follows the id converted in hex.

**Comment by genofire** [comment]
```
level="warn" msg="different linktypes" data.link="ff:dd:00:00:03:fb-ff:dd:00:00:07:3f" data.new="wifi" data.prev="vpn" data.source="wifi" data.target="vpn" caller="meshviewer.go:91 github.com/FreifunkBremen/yanic/output/meshviewer-ffrgb.transform"
```

does your data has real mac address - for the different type of link between different interfaces?

**Comment by hibo98** [comment]
No I don't get/use real mac's for anything. Has the mac's to be different? I used the generated mac of the node in all cases.

**Comment by genofire** [comment]
If there are multiple link between two nodes/neighbours, it is importent.
Otherwise it is okay, but both nodes/neighbours should announce the same **type** of link.

**Comment by xf-** [comment]
BTW hopglass-server build somewhere a version with meshviewer.json output and was included in mutli map for a short time.

**Comment by genofire** [comment]
does somebody like to try to run with the [meshviewer.json](https://data.meshviewer.org/data/meshviewer.json) from us? (or is it only backend now ?)

**Pull request merged**
