### PR TITLE
[config.toml] update ffbsee

### PR DESCRIPTION
**Pull request by DEvil0000**
different URL for Batman V firmware at bodensee

### CODE REVIEW

**Comment by genofire** [comment]
Both `meshviewer.json` are not comform ... there should not be a `.meta` and there should be `.meta.timestamp` at `.timestamp`.

---
Where you got this files from?

**Comment by DEvil0000** [comment]
We use the [map-backend.py](https://github.com/ffulm/server-config/blob/master/freifunk/map-backend.py) script from ffulm which is forked from freifunk-bielefeld.
How exactly should it look like?

**Comment by genofire** [comment]
Take a look here: [meshviewer-ffrgb](https://github.com/FreifunkBremen/yanic/blob/master/output/meshviewer-ffrgb/struct.go)

Hope this PR works and you could cherry-pick it:
https://github.com/freifunk-bielefeld/server-config/pull/6

---

- you still use alfred? (instatt of respondd / [yanic](https://github.com/FreifunkBremen/yanic) )
- maybe you want to change your install environment from a dirty shell (to ansible https://github.com/freifunk-ansible/ansible-freifunk  - https://github.com/freifunkBremen/ansible)

**Comment by DO1JLR** [comment]
Hi @genofire 

Thanks for your link.
We want to switch to respondd as soon as possible (after CCCamp). But currently we sadly use alfred.

---
I don't have much time left this month. But maybe @devil0000 or @mart-ffbsee will have a deeper look into it.

**Comment by xf-** [comment]
i updated the URL, but it is not standard formatted

Current state:
https://data.meshviewer.org/collector/

**Pull request closed without merging**
